USE ROLE ACCOUNTADMIN;


CREATE ROLE IF NOT EXISTS LOADER_ROLE
COMMENT='SERVICE ACCOUNT ROLE';

CREATE ROLE IF NOT EXISTS TRANSFORMER_ROLE
COMMENT='DBT TRANSFROMATION';

CREATE ROLE IF NOT EXISTS BI_ROLE
    COMMENT = 'Power BI service principal - read-only on MARTS';

CREATE ROLE IF NOT EXISTS DEVLOPER_ROLE
    COMMENT = 'Engineers - read all, write to DEV only';

CREATE ROLE IF NOT EXISTS ANALYST_ROLE
    COMMENT = 'Business analysts - read MARTS and INTERMEDIATE';


GRANT ROLE LOADER_ROLE TO ROLE SYSADMIN;
GRANT ROLE TRANSFORMER_ROLE TO ROLE SYSADMIN;
GRANT ROLE BI_ROLE TO ROLE SYSADMIN;
GRANT ROLE DEVLOPER_ROLE TO ROLE SYSADMIN;
GRANT ROLE ANALYST_ROLE TO ROLE SYSADMIN;

GRANT ROLE TRANSFORMER_ROLE TO USER UPRETI99;



CREATE WAREHOUSE IF NOT EXISTS LOADING_WH
WAREHOUSE_SIZE='SMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE
INITIALLY_SUSPENDED=TRUE
COMMENT = 'Dedicated compute for S3 data ingestion via COPY INTO';

CREATE WAREHOUSE IF NOT EXISTS TRANSFORMING_WH
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Dedicated compute for dbt transformations';

CREATE WAREHOUSE IF NOT EXISTS BI_WH
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Dedicated compute for Power BI queries';

CREATE WAREHOUSE IF NOT EXISTS DEV_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Developer ad-hoc queries and testing';



GRANT USAGE ON WAREHOUSE LOADING_WH TO ROLE LOADER_ROLE;
GRANT USAGE ON WAREHOUSE TRANSFORMING_WH TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON WAREHOUSE BI_WH TO ROLE BI_ROLE;
GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE DEVLOPER_ROLE;
GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE ANALYST_ROLE;



CREATE RESOURCE MONITOR IF NOT EXISTS LOADING_MONITOR
WITH CREDIT_QUOTA = 100
FREQUENCY = MONTHLY
START_TIMESTAMP = IMMEDIATELY
TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;


CREATE RESOURCE MONITOR IF NOT EXISTS TRANSFORM_MONTIOR
WITH CREDIT_QUOTA = 200
FREQUENCY = MONTHLY
START_TIMESTAMP = IMMEDIATELY
TRIGGERS 
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;


ALTER WAREHOUSE LOADING_WH SET RESOURCE_MONITOR =  LOADING_MONITOR;
ALTER WAREHOUSE TRANSFORMING_WH SET RESOURCE_MONITOR = TRANSFORM_MONTIOR;


CREATE DATABASE IF NOT EXISTS SAAS_PROD
    DATA_RETENTION_TIME_IN_DAYS = 7
    COMMENT = 'Production environment';

CREATE DATABASE IF NOT EXISTS SAAS_DEV
DATA_RETENTION_TIME_IN_DAYS = 1
COMMENT = 'Development environment - cloned from PROD weekly';


use database SAAS_PROD;

CREATE SCHEMA IF NOT EXISTS RAW
    WITH MANAGED ACCESS
    DATA_RETENTION_TIME_IN_DAYS = 14
    COMMENT = 'Landing zone - immutable source data from S3';

CREATE SCHEMA IF NOT EXISTS STAGING
    WITH MANAGED ACCESS
    DATA_RETENTION_TIME_IN_DAYS = 7
    COMMENT = 'Cleaned and typed data - 1:1 with source tables';

CREATE SCHEMA IF NOT EXISTS INTERMEDIATE
    WITH MANAGED ACCESS
    DATA_RETENTION_TIME_IN_DAYS = 7
    COMMENT = 'Cross-source joins and business logic';

CREATE SCHEMA IF NOT EXISTS MARTS
    WITH MANAGED ACCESS
    DATA_RETENTION_TIME_IN_DAYS = 14
    COMMENT = 'Final dimensional models - Power BI connects here';

CREATE SCHEMA IF NOT EXISTS UTILITY
    WITH MANAGED ACCESS
    COMMENT = 'Pipeline metadata, audit logs, helper functions';


---GRANT ACEESS TO ROLE

--Loader_role
GRANT USAGE ON DATABASE SAAS_PROD TO ROLE LOADER_ROLE;
GRANT USAGE ON SCHEMA SAAS_PROD.RAW TO ROLE LOADER_ROLE;
GRANT CREATE TABLE ON SCHEMA SAAS_PROD.RAW TO ROLE LOADER_ROLE;
GRANT CREATE STAGE ON SCHEMA SAAS_PROD.RAW TO ROLE LOADER_ROLE;
GRANT CREATE PIPE ON SCHEMA SAAS_PROD.RAW TO ROLE LOADER_ROLE;

--TRansformer role- read RAW, write STAGING/INTERMEDIATE/MARTS
GRANT USAGE ON DATABASE SAAS_PROD TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SAAS_PROD TO ROLE TRANSFORMER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SAAS_PROD.RAW TO ROLE TRANSFORMER_ROLE;
GRANT CREATE TABLE ON SCHEMA SAAS_PROD.STAGING TO ROLE TRANSFORMER_ROLE;
GRANT CREATE TABLE ON SCHEMA SAAS_PROD.INTERMEDIATE TO ROLE TRANSFORMER_ROLE;
GRANT CREATE TABLE ON SCHEMA SAAS_PROD.MARTS TO ROLE TRANSFORMER_ROLE;
GRANT CREATE VIEW ON SCHEMA SAAS_PROD.STAGING TO ROLE TRANSFORMER_ROLE;
GRANT CREATE VIEW ON SCHEMA SAAS_PROD.INTERMEDIATE TO ROLE TRANSFORMER_ROLE;
GRANT CREATE VIEW ON SCHEMA SAAS_PROD.MARTS TO ROLE TRANSFORMER_ROLE;
GRANT CREATE TASK ON SCHEMA SAAS_PROD.STAGING TO ROLE TRANSFORMER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SAAS_PROD.RAW TO ROLE TRANSFORMER_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE TRANSFORMER_ROLE;

---- BI_ROLE: read MARTS only
GRANT USAGE ON DATABASE SAAS_PROD TO ROLE BI_ROLE;
GRANT USAGE ON SCHEMA SAAS_PROD.MARTS TO ROLE BI_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SAAS_PROD.MARTS TO ROLE BI_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SAAS_PROD.MARTS TO ROLE BI_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SAAS_PROD.MARTS TO ROLE BI_ROLE;

-- ANALYST_ROLE: read MARTS + INTERMEDIATE
GRANT USAGE ON DATABASE SAAS_PROD TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA SAAS_PROD.MARTS TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA SAAS_PROD.INTERMEDIATE TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SAAS_PROD.MARTS TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SAAS_PROD.INTERMEDIATE TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SAAS_PROD.MARTS TO ROLE ANALYST_ROLE;


-- ╔══════════════════════════════════════════════════════════════════════════╗
-- ║  SECTION 5: OBJECT TAGGING (Cost Attribution & Governance)             ║
-- ╚══════════════════════════════════════════════════════════════════════════╝

USE SCHEMA SAAS_PROD.UTILITY;

CREATE TAG IF NOT EXISTS COST_CENTER
    ALLOWED_VALUES 'engineering', 'analytics', 'data-science', 'finance'
    COMMENT = 'Tag for cost attribution and chargeback';

CREATE TAG IF NOT EXISTS PII_FLAG
    ALLOWED_VALUES 'true', 'false'
    COMMENT = 'Identifies columns/tables containing PII data';

CREATE TAG IF NOT EXISTS DATA_DOMAIN
    ALLOWED_VALUES 'users', 'billing', 'product', 'support'
    COMMENT = 'Business domain ownership';

CREATE TAG IF NOT EXISTS DATA_CLASSIFICATION
    ALLOWED_VALUES 'public', 'internal', 'confidential', 'restricted'
    COMMENT = 'Data sensitivity classification';

-- Tag warehouses for cost tracking
ALTER WAREHOUSE LOADING_WH SET TAG SAAS_PROD.UTILITY.COST_CENTER = 'engineering';
ALTER WAREHOUSE TRANSFORMING_WH SET TAG SAAS_PROD.UTILITY.COST_CENTER = 'engineering';
ALTER WAREHOUSE BI_WH SET TAG SAAS_PROD.UTILITY.COST_CENTER = 'analytics';



--  Data_Masking (Masking the email and phone number from the role)


USE SCHEMA SAAS_PROD.UTILITY;

CREATE MASKING POLICY IF NOT EXISTS EMAIL_MASK AS (val STRING )
RETURNS STRING ->
CASE WHEN CURRENT_ROLE() IN ('LOADER_ROLE','TRANSFORMER_ROLE', 'ACCOUNTADMIN') THEN val
else REGEXP_REPLACE(val, '.+@', '****@')
END;


CREATE MASKING POLICY IF NOT EXISTS PHONE_MASKE AS (val STRING)
RETURNS STRING ->
CASE WHEN CURRENT_ROLE() IN ('LOADER_ROLE','TRANSFORMER_ROLE', 'ACCOUNTADMIN') THEN val
else CONCAT('-***-***', RIGHT(val,4))
END;



CREATE TASK IF NOT EXISTS SAAS_PROD.UTILITY.TASK_WEEKLY_DEV_CLONE
WAREHOUSE = DEV_WH
SCHEDULE = 'USING CRON 0 0 * * 0 UTC'
COMMENT = 'Weekly zero-copy clone of PROD into DEV for development/testing'

AS
   CREATE OR REPLACE DATABASE SAAS_DEV CLONE SAAS_PROD;

ALTER TASK SAAS_PROD.UTILITY.TASK_WEEKLY_DEV_CLONE RESUME;





















 