USE ROLE LOADER_ROLE;
USE WAREHOUSE LOADING_WH;
USE DATABASE SAAS_PROD;
USE SCHEMA RAW;

-- RAW TABLES

CREATE TABLE IF NOT EXISTS RAW_USERS (
    USER_ID             VARCHAR(50)     NOT NULL,
    EMAIL               VARCHAR(255),
    FIRST_NAME          VARCHAR(100),
    LAST_NAME           VARCHAR(100),
    PHONE               VARCHAR(30),
    SIGNUP_DATE         TIMESTAMP_NTZ,
    PLAN_TYPE           VARCHAR(50),
    STATUS              VARCHAR(20),
    COUNTRY             VARCHAR(100),
  
    LOADED_AT           TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW_SUBSCRIPTIONS (
    SUBSCRIPTION_ID     VARCHAR(50)     NOT NULL,
    USER_ID             VARCHAR(50)     NOT NULL,
    PLAN_NAME           VARCHAR(100),
    PLAN_TIER           VARCHAR(50),
    MONTHLY_PRICE       NUMBER(10,2),
    START_DATE          DATE,
    END_DATE            DATE,
    STATUS              VARCHAR(20),
    BILLING_CYCLE       VARCHAR(20),
 
    LOADED_AT           TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW_PAYMENTS (
    PAYMENT_ID          VARCHAR(50)     NOT NULL,
    SUBSCRIPTION_ID     VARCHAR(50)     NOT NULL,
    USER_ID             VARCHAR(50)     NOT NULL,
    AMOUNT              NUMBER(12,2),
    CURRENCY            VARCHAR(10),
    PAYMENT_METHOD      VARCHAR(50),
    PAYMENT_STATUS      VARCHAR(20),
    TRANSACTION_DATE    TIMESTAMP_NTZ,
    FAILURE_REASON      VARCHAR(500),

    LOADED_AT           TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW_SUPPORT_TICKETS (
    TICKET_ID           VARCHAR(50)     NOT NULL,
    USER_ID             VARCHAR(50)     NOT NULL,
    SUBJECT             VARCHAR(500),
    PRIORITY            VARCHAR(20),
    STATUS              VARCHAR(30),
    CATEGORY            VARCHAR(100),
    CREATED_AT          TIMESTAMP_NTZ,
    RESOLVED_AT         TIMESTAMP_NTZ,
    AGENT_ID            VARCHAR(50),
    SATISFACTION_SCORE  NUMBER(2,1),
 
    LOADED_AT           TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);



-- SNOWPIPES (auto-ingest from S3 via SQS event notifications)

-- After creating each pipe, run SHOW PIPES to get the SQS ARN.
-- Configure that ARN as the event notification destination on your S3 bucket.

CREATE PIPE IF NOT EXISTS PIPE_USERS
    AUTO_INGEST = TRUE
    COMMENT = 'Auto-ingest user data from S3'
    AS
    COPY INTO RAW_USERS (
        USER_ID, EMAIL, FIRST_NAME, LAST_NAME, PHONE,
        SIGNUP_DATE, PLAN_TYPE, STATUS, COUNTRY
    )
    FROM @STG_USERS
    FILE_FORMAT = (FORMAT_NAME = CSV_STANDARD)
    ON_ERROR = 'SKIP_FILE';

CREATE PIPE IF NOT EXISTS PIPE_SUBSCRIPTIONS
    AUTO_INGEST = TRUE
    COMMENT = 'Auto-ingest subscription data from S3'
    AS
    COPY INTO RAW_SUBSCRIPTIONS (
        SUBSCRIPTION_ID, USER_ID, PLAN_NAME, PLAN_TIER, MONTHLY_PRICE,
        START_DATE, END_DATE, STATUS, BILLING_CYCLE
    )
    FROM @STG_SUBSCRIPTIONS
    FILE_FORMAT = (FORMAT_NAME = CSV_STANDARD)
    ON_ERROR = 'SKIP_FILE';

CREATE PIPE IF NOT EXISTS PIPE_PAYMENTS
    AUTO_INGEST = TRUE
    COMMENT = 'Auto-ingest payment data from S3'
    AS
    COPY INTO RAW_PAYMENTS (
        PAYMENT_ID, SUBSCRIPTION_ID, USER_ID, AMOUNT, CURRENCY,
        PAYMENT_METHOD, PAYMENT_STATUS, TRANSACTION_DATE, FAILURE_REASON
    )
    FROM @STG_PAYMENTS
    FILE_FORMAT = (FORMAT_NAME = CSV_STANDARD)
    ON_ERROR = 'SKIP_FILE';

CREATE PIPE IF NOT EXISTS PIPE_SUPPORT_TICKETS
    AUTO_INGEST = TRUE
    COMMENT = 'Auto-ingest support ticket data from S3'
    AS
    COPY INTO RAW_SUPPORT_TICKETS (
        TICKET_ID, USER_ID, SUBJECT, PRIORITY, STATUS,
        CATEGORY, CREATED_AT, RESOLVED_AT, AGENT_ID, SATISFACTION_SCORE
    )
    FROM @STG_SUPPORT_TICKETS
    FILE_FORMAT = (FORMAT_NAME = CSV_STANDARD)
    ON_ERROR = 'SKIP_FILE';



-- GET SQS NOTIFICATION CHANNEL ARN (needed for S3 bucket event config)


SHOW PIPES IN SCHEMA SAAS_PROD.RAW;



-- MONITORING QUERIES (run after data starts flowing)


-- Check pipe status
SELECT SYSTEM$PIPE_STATUS('SAAS_PROD.RAW.PIPE_USERS');
 SELECT SYSTEM$PIPE_STATUS('SAAS_PROD.RAW.PIPE_SUBSCRIPTIONS');
SELECT SYSTEM$PIPE_STATUS('SAAS_PROD.RAW.PIPE_PAYMENTS');
SELECT SYSTEM$PIPE_STATUS('SAAS_PROD.RAW.PIPE_SUPPORT_TICKETS');

-- Check ingestion history (last 24 hours)
-- SELECT *
-- FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
--     TABLE_NAME => 'RAW_USERS',
--     START_TIME => DATEADD(HOUR, -24, CURRENT_TIMESTAMP())
-- ));

ALTER PIPE SAAS_PROD.RAW.PIPE_USERS REFRESH;

ALTER PIPE SAAS_PROD.RAW.PIPE_PAYMENTS REFRESH;

ALTER PIPE SAAS_PROD.RAW.PIPE_SUBSCRIPTIONS REFRESH;

ALTER PIPE SAAS_PROD.RAW.PIPE_SUPPORT_TICKETS REFRESH;

select * from RAW_SUPPORT_TICKETS;
select * from RAW_PAYMENTS;
SELECT * FROM RAW_USERS;
SELECT * FROM RAW_SUBSCRIPTIONS;
