USE ROLE TRANSFORMER_ROLE;
USE WAREHOUSE TRANSFORMING_WH;
USE DATABASE SAAS_PROD;


-- STREAMS (capture inserts/updates/deletes on RAW tables)


USE SCHEMA RAW;



CREATE STREAM IF NOT EXISTS STREAM_RAW_USERS
    ON TABLE RAW_USERS
    APPEND_ONLY = FALSE
    SHOW_INITIAL_ROWS = TRUE
    COMMENT = 'CDC stream on RAW_USERS - captures all DML changes';

CREATE STREAM IF NOT EXISTS STREAM_RAW_SUBSCRIPTIONS
    ON TABLE RAW_SUBSCRIPTIONS
    APPEND_ONLY = FALSE
    SHOW_INITIAL_ROWS = TRUE
    COMMENT = 'CDC stream on RAW_SUBSCRIPTIONS';

CREATE STREAM IF NOT EXISTS STREAM_RAW_PAYMENTS
    ON TABLE RAW_PAYMENTS
    APPEND_ONLY = TRUE
    SHOW_INITIAL_ROWS = TRUE
    COMMENT = 'CDC stream on RAW_PAYMENTS - append only (payments are immutable)';

CREATE STREAM IF NOT EXISTS STREAM_RAW_SUPPORT_TICKETS
    ON TABLE RAW_SUPPORT_TICKETS
    APPEND_ONLY = FALSE
    SHOW_INITIAL_ROWS = TRUE
    COMMENT = 'CDC stream on RAW_SUPPORT_TICKETS';


-- STAGING TABLES (cleaned, typed, deduplicated)


USE SCHEMA STAGING;

CREATE TABLE IF NOT EXISTS STG_USERS (
    USER_ID             VARCHAR(50)     NOT NULL,
    EMAIL               VARCHAR(255),
    FIRST_NAME          VARCHAR(100),
    LAST_NAME           VARCHAR(100),
    PHONE               VARCHAR(30),
    SIGNUP_DATE         TIMESTAMP_NTZ,
    PLAN_TYPE           VARCHAR(50),
    STATUS              VARCHAR(20),
    COUNTRY             VARCHAR(100),
    LOADED_AT           TIMESTAMP_NTZ,
    UPDATED_AT          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS STG_SUBSCRIPTIONS (
    SUBSCRIPTION_ID     VARCHAR(50)     NOT NULL,
    USER_ID             VARCHAR(50)     NOT NULL,
    PLAN_NAME           VARCHAR(100),
    PLAN_TIER           VARCHAR(50),
    MONTHLY_PRICE       NUMBER(10,2),
    START_DATE          DATE,
    END_DATE            DATE,
    STATUS              VARCHAR(20),
    BILLING_CYCLE       VARCHAR(20),
    LOADED_AT           TIMESTAMP_NTZ,
    UPDATED_AT          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SUBSCRIPTION_ID)
);

CREATE TABLE IF NOT EXISTS STG_PAYMENTS (
    PAYMENT_ID          VARCHAR(50)     NOT NULL,
    SUBSCRIPTION_ID     VARCHAR(50)     NOT NULL,
    USER_ID             VARCHAR(50)     NOT NULL,
    AMOUNT              NUMBER(12,2),
    CURRENCY            VARCHAR(10),
    PAYMENT_METHOD      VARCHAR(50),
    PAYMENT_STATUS      VARCHAR(20),
    TRANSACTION_DATE    TIMESTAMP_NTZ,
    FAILURE_REASON      VARCHAR(500),
    LOADED_AT           TIMESTAMP_NTZ,
    UPDATED_AT          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PAYMENT_ID)
);

CREATE TABLE IF NOT EXISTS STG_SUPPORT_TICKETS (
    TICKET_ID           VARCHAR(50)     NOT NULL,
    USER_ID             VARCHAR(50)     NOT NULL,
    SUBJECT             VARCHAR(500),
    PRIORITY            VARCHAR(20),
    STATUS              VARCHAR(30),
    CATEGORY            VARCHAR(100),
    CREATED_AT          TIMESTAMP_NTZ,
    RESOLVED_AT         TIMESTAMP_NTZ,
    AGENT_ID            VARCHAR(50),
    SATISFACTION_SCORE  NUMBER(2,1),
    LOADED_AT           TIMESTAMP_NTZ,
    UPDATED_AT          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (TICKET_ID)
);




-- TASKS (MERGE stream data into STAGING every 5 minutes)


CREATE TASK IF NOT EXISTS TASK_MERGE_USERS
    WAREHOUSE = TRANSFORMING_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('SAAS_PROD.RAW.STREAM_RAW_USERS')
    AS
    MERGE INTO SAAS_PROD.STAGING.STG_USERS AS tgt
    USING (
        SELECT *
        FROM SAAS_PROD.RAW.STREAM_RAW_USERS
        QUALIFY ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY LOADED_AT DESC) = 1
    ) AS src
    ON tgt.USER_ID = src.USER_ID
    WHEN MATCHED AND src.METADATA$ACTION = 'INSERT' THEN UPDATE SET
        tgt.EMAIL = src.EMAIL,
        tgt.FIRST_NAME = src.FIRST_NAME,
        tgt.LAST_NAME = src.LAST_NAME,
        tgt.PHONE = src.PHONE,
        tgt.SIGNUP_DATE = src.SIGNUP_DATE,
        tgt.PLAN_TYPE = src.PLAN_TYPE,
        tgt.STATUS = src.STATUS,
        tgt.COUNTRY = src.COUNTRY,
        tgt.LOADED_AT = src.LOADED_AT,
        tgt.UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED AND src.METADATA$ACTION = 'INSERT' THEN INSERT (
        USER_ID, EMAIL, FIRST_NAME, LAST_NAME, PHONE,
        SIGNUP_DATE, PLAN_TYPE, STATUS, COUNTRY,
        LOADED_AT, UPDATED_AT
    ) VALUES (
        src.USER_ID, src.EMAIL, src.FIRST_NAME, src.LAST_NAME, src.PHONE,
        src.SIGNUP_DATE, src.PLAN_TYPE, src.STATUS, src.COUNTRY,
        src.LOADED_AT, CURRENT_TIMESTAMP()
    );


CREATE TASK IF NOT EXISTS TASK_MERGE_SUBSCRIPTIONS
    WAREHOUSE = TRANSFORMING_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('SAAS_PROD.RAW.STREAM_RAW_SUBSCRIPTIONS')
    AS
    MERGE INTO SAAS_PROD.STAGING.STG_SUBSCRIPTIONS AS tgt
    USING (
        SELECT *
        FROM SAAS_PROD.RAW.STREAM_RAW_SUBSCRIPTIONS
        QUALIFY ROW_NUMBER() OVER (PARTITION BY SUBSCRIPTION_ID ORDER BY LOADED_AT DESC) = 1
    ) AS src
    ON tgt.SUBSCRIPTION_ID = src.SUBSCRIPTION_ID
    WHEN MATCHED AND src.METADATA$ACTION = 'INSERT' THEN UPDATE SET
        tgt.USER_ID = src.USER_ID,
        tgt.PLAN_NAME = src.PLAN_NAME,
        tgt.PLAN_TIER = src.PLAN_TIER,
        tgt.MONTHLY_PRICE = src.MONTHLY_PRICE,
        tgt.START_DATE = src.START_DATE,
        tgt.END_DATE = src.END_DATE,
        tgt.STATUS = src.STATUS,
        tgt.BILLING_CYCLE = src.BILLING_CYCLE,
        tgt.LOADED_AT = src.LOADED_AT,
        tgt.UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED AND src.METADATA$ACTION = 'INSERT' THEN INSERT (
        SUBSCRIPTION_ID, USER_ID, PLAN_NAME, PLAN_TIER, MONTHLY_PRICE,
        START_DATE, END_DATE, STATUS, BILLING_CYCLE,
        LOADED_AT, UPDATED_AT
    ) VALUES (
        src.SUBSCRIPTION_ID, src.USER_ID, src.PLAN_NAME, src.PLAN_TIER, src.MONTHLY_PRICE,
        src.START_DATE, src.END_DATE, src.STATUS, src.BILLING_CYCLE,
        src.LOADED_AT, CURRENT_TIMESTAMP()
    );


CREATE TASK IF NOT EXISTS TASK_MERGE_PAYMENTS
    WAREHOUSE = TRANSFORMING_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('SAAS_PROD.RAW.STREAM_RAW_PAYMENTS')
    AS
    MERGE INTO SAAS_PROD.STAGING.STG_PAYMENTS AS tgt
    USING (
        SELECT *
        FROM SAAS_PROD.RAW.STREAM_RAW_PAYMENTS
    ) AS src
    ON tgt.PAYMENT_ID = src.PAYMENT_ID
    WHEN NOT MATCHED THEN INSERT (
        PAYMENT_ID, SUBSCRIPTION_ID, USER_ID, AMOUNT, CURRENCY,
        PAYMENT_METHOD, PAYMENT_STATUS, TRANSACTION_DATE, FAILURE_REASON,
        LOADED_AT, UPDATED_AT
    ) VALUES (
        src.PAYMENT_ID, src.SUBSCRIPTION_ID, src.USER_ID, src.AMOUNT, src.CURRENCY,
        src.PAYMENT_METHOD, src.PAYMENT_STATUS, src.TRANSACTION_DATE, src.FAILURE_REASON,
        src.LOADED_AT, CURRENT_TIMESTAMP()
    );


CREATE TASK IF NOT EXISTS TASK_MERGE_SUPPORT_TICKETS
    WAREHOUSE = TRANSFORMING_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('SAAS_PROD.RAW.STREAM_RAW_SUPPORT_TICKETS')
    AS
    MERGE INTO SAAS_PROD.STAGING.STG_SUPPORT_TICKETS AS tgt
    USING (
        SELECT *
        FROM SAAS_PROD.RAW.STREAM_RAW_SUPPORT_TICKETS
        QUALIFY ROW_NUMBER() OVER (PARTITION BY TICKET_ID ORDER BY LOADED_AT DESC) = 1
    ) AS src
    ON tgt.TICKET_ID = src.TICKET_ID
    WHEN MATCHED AND src.METADATA$ACTION = 'INSERT' THEN UPDATE SET
        tgt.USER_ID = src.USER_ID,
        tgt.SUBJECT = src.SUBJECT,
        tgt.PRIORITY = src.PRIORITY,
        tgt.STATUS = src.STATUS,
        tgt.CATEGORY = src.CATEGORY,
        tgt.CREATED_AT = src.CREATED_AT,
        tgt.RESOLVED_AT = src.RESOLVED_AT,
        tgt.AGENT_ID = src.AGENT_ID,
        tgt.SATISFACTION_SCORE = src.SATISFACTION_SCORE,
        tgt.LOADED_AT = src.LOADED_AT,
        tgt.UPDATED_AT = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED AND src.METADATA$ACTION = 'INSERT' THEN INSERT (
        TICKET_ID, USER_ID, SUBJECT, PRIORITY, STATUS,
        CATEGORY, CREATED_AT, RESOLVED_AT, AGENT_ID, SATISFACTION_SCORE,
        LOADED_AT, UPDATED_AT
    ) VALUES (
        src.TICKET_ID, src.USER_ID, src.SUBJECT, src.PRIORITY, src.STATUS,
        src.CATEGORY, src.CREATED_AT, src.RESOLVED_AT, src.AGENT_ID, src.SATISFACTION_SCORE,
        src.LOADED_AT, CURRENT_TIMESTAMP()
    );



-- RESUME TASKS (tasks are created in suspended state by default)


ALTER TASK TASK_MERGE_USERS RESUME;
ALTER TASK TASK_MERGE_SUBSCRIPTIONS RESUME;
ALTER TASK TASK_MERGE_PAYMENTS RESUME;
ALTER TASK TASK_MERGE_SUPPORT_TICKETS RESUME;


-- MONITORING


-- Check if streams have unconsumed data
SELECT SYSTEM$STREAM_HAS_DATA('SAAS_PROD.RAW.STREAM_RAW_PAYMENTS');


-- APPLY DYNAMIC MASKING POLICIES ON STAGING (defined in 1.sql)
-- Protects EMAIL and PHONE from BI_ROLE, ANALYST_ROLE, DEVLOPER_ROLE
-- LOADER_ROLE, TRANSFORMER_ROLE, and ACCOUNTADMIN see full values


USE ROLE ACCOUNTADMIN;

ALTER TABLE SAAS_PROD.STAGING.STG_USERS
    MODIFY COLUMN EMAIL SET MASKING POLICY SAAS_PROD.UTILITY.EMAIL_MASK;

ALTER TABLE SAAS_PROD.STAGING.STG_USERS
    MODIFY COLUMN PHONE SET MASKING POLICY SAAS_PROD.UTILITY.PHONE_MASKE;



-- DATA METRIC FUNCTIONS (Built-in DMFs for runtime quality monitoring)
-- These run automatically on change and surface in DATA_QUALITY_MONITORING_RESULTS

--  STG_USERS: Monitor primary key integrity and critical field nulls   


ALTER TABLE SAAS_PROD.STAGING.STG_USERS
    SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';

ALTER TABLE SAAS_PROD.STAGING.STG_USERS
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (USER_ID);

ALTER TABLE SAAS_PROD.STAGING.STG_USERS
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (EMAIL);

ALTER TABLE SAAS_PROD.STAGING.STG_USERS
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (STATUS);

ALTER TABLE SAAS_PROD.STAGING.STG_USERS
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (USER_ID);

ALTER TABLE SAAS_PROD.STAGING.STG_USERS
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (EMAIL);

ALTER TABLE SAAS_PROD.STAGING.STG_USERS
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();



--   STG_SUBSCRIPTIONS: PK uniqueness, FK integrity, null monitoring     


ALTER TABLE SAAS_PROD.STAGING.STG_SUBSCRIPTIONS
    SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';

ALTER TABLE SAAS_PROD.STAGING.STG_SUBSCRIPTIONS
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (SUBSCRIPTION_ID);

ALTER TABLE SAAS_PROD.STAGING.STG_SUBSCRIPTIONS
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (USER_ID);

ALTER TABLE SAAS_PROD.STAGING.STG_SUBSCRIPTIONS
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (PLAN_TIER);

ALTER TABLE SAAS_PROD.STAGING.STG_SUBSCRIPTIONS
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (SUBSCRIPTION_ID);

ALTER TABLE SAAS_PROD.STAGING.STG_SUBSCRIPTIONS
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();



---  STG_PAYMENTS: PK uniqueness, amount nulls, freshness  


ALTER TABLE SAAS_PROD.STAGING.STG_PAYMENTS
    SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';

ALTER TABLE SAAS_PROD.STAGING.STG_PAYMENTS
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (PAYMENT_ID);

ALTER TABLE SAAS_PROD.STAGING.STG_PAYMENTS
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (USER_ID);

ALTER TABLE SAAS_PROD.STAGING.STG_PAYMENTS
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (AMOUNT);

ALTER TABLE SAAS_PROD.STAGING.STG_PAYMENTS
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (PAYMENT_STATUS);

ALTER TABLE SAAS_PROD.STAGING.STG_PAYMENTS
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (PAYMENT_ID);

ALTER TABLE SAAS_PROD.STAGING.STG_PAYMENTS
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();



-- STG_SUPPORT_TICKETS: PK uniqueness, priority nulls, freshness


ALTER TABLE SAAS_PROD.STAGING.STG_SUPPORT_TICKETS
    SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';

ALTER TABLE SAAS_PROD.STAGING.STG_SUPPORT_TICKETS
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (TICKET_ID);

ALTER TABLE SAAS_PROD.STAGING.STG_SUPPORT_TICKETS
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (USER_ID);

ALTER TABLE SAAS_PROD.STAGING.STG_SUPPORT_TICKETS
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (PRIORITY);

ALTER TABLE SAAS_PROD.STAGING.STG_SUPPORT_TICKETS
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (STATUS);

ALTER TABLE SAAS_PROD.STAGING.STG_SUPPORT_TICKETS
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT ON (TICKET_ID);

ALTER TABLE SAAS_PROD.STAGING.STG_SUPPORT_TICKETS
    ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();


-- ════════════════════════════════════════════════════════════════════════════
-- QUERY DMF RESULTS (run after data flows through)
-- ════════════════════════════════════════════════════════════════════════════

-- View all quality metric results for STAGING schema
-- SELECT *
-- FROM SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS
-- WHERE TABLE_SCHEMA = 'STAGING'
--   AND TABLE_DATABASE = 'SAAS_PROD'
-- ORDER BY MEASUREMENT_TIME DESC
-- LIMIT 50;

-- View only FAILURES (non-zero values indicate quality issues)
-- SELECT *
-- FROM SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS
-- WHERE TABLE_SCHEMA = 'STAGING'
--   AND TABLE_DATABASE = 'SAAS_PROD'
--   AND VALUE > 0
-- ORDER BY MEASUREMENT_TIME DESC;



-- VERIFICATION QUERIES
SELECT * FROM SAAS_PROD.STAGING.STG_USERS ORDER BY USER_ID;
SELECT * FROM SAAS_PROD.STAGING.STG_PAYMENTS ORDER BY PAYMENT_ID;





select * from saas_prod.INTERMEDIATE.SUPPORT_TICKET_CLEANED
where STATUS = 'RESOLVED'
  AND RESOLVED_AT IS NULL


UPDATE saas_prod.intermediate.support_ticket_cleaned
SET RESOLUTION_AT = CURRENT_TIMESTAMP()
WHERE TICKET_ID = 'T27';