
USE ROLE ACCOUNTADMIN;
USE DATABASE SAAS_PROD;
USE SCHEMA UTILITY;


CREATE NOTIFICATION INTEGRATION IF NOT EXISTS EMAIL_ALERT
TYPE= EMAIL 
ENABLED = TRUE
ALLOWED_RECIPIENTS = ('tarunupreti00@gmail.com')
COMMENT = 'Email notificationss for pipeline failures and data quality alerts';


CREATE OR REPLACE ALERT ALERT_TASK_FAILURE
WAREHOUSE= TRANSFORMING_WH
SCHEDULE = '120 MINUTE'
IF (EXISTS (
        SELECT 1
        FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
            SCHEDULED_TIME_RANGE_START => DATEADD('hour', -2, CURRENT_TIMESTAMP()),
            RESULT_LIMIT => 50
        ))
        WHERE STATE = 'FAILED'
          AND DATABASE_NAME = 'SAAS_PROD'
    ))
    THEN
        CALL SYSTEM$SEND_EMAIL(
            'EMAIL_ALERT',
            'tarunupreti00@gmail.com',
            'ALERT: SAAS_PROD Task Failure',
            'A CDC task failed in the last 2 hours.\n\nCheck: SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY()) WHERE STATE = ''FAILED'' ORDER BY SCHEDULED_TIME DESC LIMIT 10;' );


ALTER ALERT ALERT_TASK_FAILURE RESUME;


GRANT USAGE ON SCHEMA SAAS_PROD.UTILITY TO ROLE TRANSFORMER_ROLE;
GRANT USAGE ON SCHEMA SAAS_PROD.UTILITY TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA SAAS_PROD.UTILITY TO ROLE TRANSFORMER_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA SAAS_PROD.UTILITY TO ROLE ANALYST_ROLE;


