{{ config(materialized='table') }}

WITH users AS (
SELECT * FROM {{ ref('user_cleaned') }}
),
current_subscriptions AS (
SELECT USER_ID,
PLAN_TIER,
STATUS AS SUBSCRIPTION_STATUS
    
FROM {{ ref('subscription_cleaned') }}
QUALIFY ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY START_DATE DESC) = 1
)

SELECT u.USER_ID, u.EMAIL,
u.FIRST_NAME, u.LAST_NAME,
u.PHONE, u.COUNTRY,
u.SIGNUP_DATE,
u.STATUS AS USER_STATUS,
COALESCE(cs.PLAN_TIER, 'FREE') AS CURRENT_PLAN_TIER,
COALESCE(cs.SUBSCRIPTION_STATUS, 'NOT_SUBSCRIBED') AS SUBSCRIPTION_STATUS,
CASE WHEN cs.SUBSCRIPTION_STATUS = 'ACTIVE' THEN TRUE 
ELSE FALSE END AS IS_PAYING,

DATEDIFF('day', u.SIGNUP_DATE, CURRENT_TIMESTAMP()) AS DAYS_SINCE_SIGNUP
FROM users u
LEFT JOIN current_subscriptions cs 
ON u.USER_ID = cs.USER_ID
