
{{ config(materialized='table') }}

WITH plans AS (
SELECT DISTINCT PLAN_NAME,
PLAN_TIER,
BILLING_CYCLE,
MONTHLY_PRICE
    
FROM {{ ref('subscription_cleaned') }}
)

SELECT PLAN_NAME, PLAN_TIER,
BILLING_CYCLE,
MONTHLY_PRICE,
CASE
    WHEN PLAN_TIER = 'GOLD' THEN 1
    WHEN PLAN_TIER = 'PLATINUM' THEN 2
    WHEN PLAN_TIER = 'DIAMOND' THEN 3
    WHEN PLAN_TIER = 'SILVER' THEN 4
    ELSE 5
END AS TIER_ORDER

FROM plans
