{{ config(materialized='table') }}

WITH date_spine AS (
    SELECT
        DATEADD('day', SEQ4(), '2020-01-01')::DATE AS FULL_DATE
    FROM TABLE(GENERATOR(ROWCOUNT => 3650))
)

SELECT
TO_NUMBER(TO_CHAR(FULL_DATE, 'YYYYMMDD')) AS DATE_KEY,
FULL_DATE,
DAYOFMONTH(FULL_DATE) AS DAY,
MONTH(FULL_DATE) AS MONTH,
MONTHNAME(FULL_DATE) AS MONTH_NAME,
QUARTER(FULL_DATE) AS QUARTER,
YEAR(FULL_DATE) AS YEAR,
DAYNAME(FULL_DATE) AS DAY_NAME,
DAYOFWEEK(FULL_DATE) AS DAY_OF_WEEK,
CASE WHEN DAYOFWEEK(FULL_DATE) IN (0, 6) THEN TRUE 
ELSE FALSE 
END AS IS_WEEKEND
FROM date_spine