{{
    config(
        materialized='incremental',
        unique_key='SUBSCRIPTION_ID',
        incremental_strategy='merge'
    )
}}

WITH snapshot_data AS (
SELECT * FROM {{ ref('snap_subscription') }}
{% if is_incremental() %}
    WHERE DBT_UPDATED_AT > (SELECT MAX(EFFECTIVE_FROM) FROM {{ this }})
{% endif %}
)

SELECT SUBSCRIPTION_ID,
USER_ID,
PLAN_NAME,
PLAN_TIER,
MONTHLY_PRICE,
BILLING_CYCLE,

STATUS AS SUBSCRIPTION_STATUS,
DBT_VALID_FROM AS EFFECTIVE_FROM,
DBT_VALID_TO AS EFFECTIVE_TO,
DBT_VALID_FROM::DATE AS EFFECTIVE_FROM_DATE_KEY,
    
CASE WHEN DBT_VALID_TO IS NULL THEN TRUE
     ELSE FALSE
END AS IS_CURRENT,
    
DATEDIFF('day', START_DATE, COALESCE(END_DATE, CURRENT_DATE())) AS DAYS_IN_STATE,
CASE
    WHEN BILLING_CYCLE = 'YEARLY' THEN MONTHLY_PRICE
    ELSE MONTHLY_PRICE
END AS MRR_CONTRIBUTION

FROM snapshot_data
