{{
config(
        materialized='incremental',
        unique_key='TICKET_ID',
        incremental_strategy='merge'
    )
}}

WITH tickets AS (

SELECT * FROM {{ ref('support_ticket_cleaned') }}
{% if is_incremental() %}
    WHERE UPDATED_AT > (SELECT MAX(LOADED_AT) FROM {{ this }})
{% endif %}

)

SELECT TICKET_ID, USER_ID,
SUBJECT,
PRIORITY,
STATUS AS TICKET_STATUS,
CATEGORY, CREATED_AT,
RESOLVED_AT,
CREATED_AT::DATE AS CREATED_DATE_KEY,
AGENT_ID,
SATISFACTION_SCORE,
    
DATEDIFF('hour', CREATED_AT, RESOLVED_AT) AS RESOLUTION_HOURS,

CASE WHEN STATUS = 'RESOLVED' THEN TRUE ELSE FALSE END AS IS_RESOLVED,
CASE
   WHEN PRIORITY = 'HIGH' AND DATEDIFF('hour', CREATED_AT, RESOLVED_AT) > 24 THEN TRUE
   WHEN PRIORITY = 'MEDIUM' AND DATEDIFF('hour', CREATED_AT, RESOLVED_AT) > 48 THEN TRUE
   WHEN PRIORITY = 'LOW' AND DATEDIFF('hour', CREATED_AT, RESOLVED_AT) > 72 THEN TRUE
    ELSE FALSE
END AS SLA_BREACHED,

    LOADED_AT
    
FROM tickets
