name: SAAS_DBT
version: 1.0.0
config-version: 2
profile: SAAS_DBT
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots

models:
  SAAS_DBT:

    intermediate:
      +materialized: view
      +schema: INTERMEDIATE

    marts:
      +materialized: table
      +schema: MARTS
